#pragma once
#include <lvgl.h>

// Seen Health spinning-logo boot animation. The pixel data lives in
// flash (see seen_logo_frames.h, generated by tools/convert_seen_logo.py)
// and is exposed through an LVGL image descriptor per frame.

void                    seen_logo_init(void);
int                     seen_logo_frame_count(void);
const lv_image_dsc_t*   seen_logo_frame(int idx);
