#!/usr/bin/env python3
"""Convert the Seen Health spinning-logo PNG sequence into a C header of
RGB565 frame arrays. Picks every Nth frame, scales each to a square
target size, composites RGBA over black (since the LCD background is
true black), and emits one `uint16_t seen_logo_frame_NN[]` per frame
plus a frame index table.

Run from anywhere; the script writes
  firmware/src/seen_logo_frames.h
"""
import sys
from pathlib import Path
from PIL import Image

SRC_DIR = Path("/Users/johnzheng/Developer/SeenHealth/Resource/seen_logo_spin_frames")
OUT_FILE = Path(__file__).resolve().parent.parent / "src" / "seen_logo_frames.h"

FRAME_COUNT = 30          # picked from the 120 source frames
TARGET_SIZE = 144         # 144x144 px — fits the prism visible area with margin

def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

def convert_frame(path: Path) -> list[int]:
    img = Image.open(path).convert("RGBA")
    img = img.resize((TARGET_SIZE, TARGET_SIZE), Image.LANCZOS)
    # Composite over black so the alpha turns into a clean blend with
    # the LCD's #000 background.
    bg = Image.new("RGB", img.size, (0, 0, 0))
    bg.paste(img, mask=img.split()[3])
    px = bg.load()
    out = []
    for y in range(TARGET_SIZE):
        for x in range(TARGET_SIZE):
            r, g, b = px[x, y]
            out.append(rgb565(r, g, b))
    return out

def main() -> int:
    frames = sorted(SRC_DIR.glob("seen_logo_spin_*.png"))
    if not frames:
        print(f"No frames found in {SRC_DIR}", file=sys.stderr)
        return 1
    step = max(1, len(frames) // FRAME_COUNT)
    selected = frames[::step][:FRAME_COUNT]
    print(f"Selecting {len(selected)} / {len(frames)} frames (step={step}), "
          f"target {TARGET_SIZE}x{TARGET_SIZE}")

    lines: list[str] = []
    lines.append("// Auto-generated by tools/convert_seen_logo.py — do not hand-edit.")
    lines.append("// Seen Health spinning-logo boot animation.")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("#include <pgmspace.h>")
    lines.append("")
    lines.append(f"#define SEEN_LOGO_W {TARGET_SIZE}")
    lines.append(f"#define SEEN_LOGO_H {TARGET_SIZE}")
    lines.append(f"#define SEEN_LOGO_FRAME_COUNT {len(selected)}")
    lines.append("")

    px_per_frame = TARGET_SIZE * TARGET_SIZE
    for idx, path in enumerate(selected):
        data = convert_frame(path)
        assert len(data) == px_per_frame
        lines.append(f"static const uint16_t seen_logo_frame_{idx:02d}[{px_per_frame}] PROGMEM = {{")
        # 16 values per line keeps the file readable.
        for i in range(0, px_per_frame, 16):
            row = ", ".join(f"0x{v:04X}" for v in data[i:i+16])
            lines.append(f"    {row},")
        lines.append("};")
        lines.append("")

    lines.append("static const uint16_t* const SEEN_LOGO_FRAMES[SEEN_LOGO_FRAME_COUNT] = {")
    for idx in range(len(selected)):
        lines.append(f"    seen_logo_frame_{idx:02d},")
    lines.append("};")
    lines.append("")

    OUT_FILE.write_text("\n".join(lines))
    print(f"Wrote {OUT_FILE} ({OUT_FILE.stat().st_size // 1024} KB)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
